// Adds microphone permission to the generated Android project.
// `src-tauri/gen/android` is regenerated by `tauri android init`, so this runs
// after every init (locally and in CI) instead of being committed.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const manifest = "src-tauri/gen/android/app/src/main/AndroidManifest.xml";

if (!existsSync(manifest)) {
  console.error(`[patch-android] ${manifest} not found — run "tauri android init" first`);
  process.exit(1);
}

let xml = readFileSync(manifest, "utf8");
let changed = false;

const permissions = [
  '<uses-permission android:name="android.permission.RECORD_AUDIO" />',
  '<uses-feature android:name="android.hardware.microphone" android:required="false" />',
];

for (const line of permissions) {
  if (!xml.includes(line.split(" ")[1])) {
    xml = xml.replace("<application", `    ${line}\n\n    <application`);
    changed = true;
  }
}

// A gateway reachable only by IP has no certificate a phone will accept, so
// a build pointed at one talks plain HTTP. Android forbids that by default
// and fails with a connection error that names nothing. This allows it for
// the app's own traffic only — and only matters when the build's gateway
// address is an http:// one, which the server's own README argues against.
const gateway = process.env.VD_CLOUD_BASE_URL ?? "";
if (gateway.startsWith("http://") && !xml.includes("usesCleartextTraffic")) {
  xml = xml.replace("<application", '<application android:usesCleartextTraffic="true"');
  changed = true;
  console.warn(
    "[patch-android] VD_CLOUD_BASE_URL is http:// — cleartext enabled; " +
      "licence keys and chats will travel unencrypted",
  );
}

if (changed) {
  writeFileSync(manifest, xml);
  console.log("[patch-android] manifest patched");
} else {
  console.log("[patch-android] manifest already patched");
}
