// Adds microphone permission to the generated Android project.
// `src-tauri/gen/android` is regenerated by `tauri android init`, so this runs
// after every init (locally and in CI) instead of being committed.
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const manifest = "src-tauri/gen/android/app/src/main/AndroidManifest.xml";

if (!existsSync(manifest)) {
  console.error(`[patch-android] ${manifest} not found — run "tauri android init" first`);
  process.exit(1);
}

let xml = readFileSync(manifest, "utf8");
let changed = false;

const permissions = [
  '<uses-permission android:name="android.permission.RECORD_AUDIO" />',
  '<uses-feature android:name="android.hardware.microphone" android:required="false" />',
];

for (const line of permissions) {
  if (!xml.includes(line.split(" ")[1])) {
    xml = xml.replace("<application", `    ${line}\n\n    <application`);
    changed = true;
  }
}

if (changed) {
  writeFileSync(manifest, xml);
  console.log("[patch-android] microphone permission added");
} else {
  console.log("[patch-android] manifest already patched");
}
