// Adds microphone permission to the generated Android project.
// `src-tauri/gen/android` is regenerated by `tauri android init`, so this runs
// after every init (locally and in CI) instead of being committed.
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const manifest = "src-tauri/gen/android/app/src/main/AndroidManifest.xml";

if (!existsSync(manifest)) {
  console.error(`[patch-android] ${manifest} not found — run "tauri android init" first`);
  process.exit(1);
}

let xml = readFileSync(manifest, "utf8");
let changed = false;

const permissions = [
  '<uses-permission android:name="android.permission.RECORD_AUDIO" />',
  '<uses-feature android:name="android.hardware.microphone" android:required="false" />',
];

for (const line of permissions) {
  if (!xml.includes(line.split(" ")[1])) {
    xml = xml.replace("<application", `    ${line}\n\n    <application`);
    changed = true;
  }
}

// A gateway reachable only by IP has no certificate a phone will accept, so
// a build pointed at one talks plain HTTP. Android forbids that by default
// and fails with a connection error that names nothing. This allows it for
// the app's own traffic only — and only matters when the build's gateway
// address is an http:// one, which the server's own README argues against.
const gateway = process.env.VD_CLOUD_BASE_URL ?? "";
if (gateway.startsWith("http://") && !xml.includes("usesCleartextTraffic")) {
  xml = xml.replace("<application", '<application android:usesCleartextTraffic="true"');
  changed = true;
  console.warn(
    "[patch-android] VD_CLOUD_BASE_URL is http:// — cleartext enabled; " +
      "licence keys and chats will travel unencrypted",
  );
}

if (changed) {
  writeFileSync(manifest, xml);
  console.log("[patch-android] manifest patched");
} else {
  console.log("[patch-android] manifest already patched");
}

// The window and the system bars.
//
// The generated activity draws the page edge to edge, under the status bar and
// the gesture bar, and the Android WebView does not report how tall those are
// to the page: `env(safe-area-inset-top)` comes back as zero, so the top bar
// sat under the clock and the battery. The activity is replaced with one that
// takes the bars' height — and the keyboard's, which edge to edge would
// otherwise cover the composer with — out of the page's box, and paints that
// strip the colour of the app's own bars with light icons on it.
function findActivity(dir) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      const found = findActivity(path);
      if (found) return found;
    } else if (name === "MainActivity.kt") {
      return path;
    }
  }
  return null;
}

const activity = findActivity("src-tauri/gen/android/app/src/main/java");
if (!activity) {
  console.error("[patch-android] MainActivity.kt not found");
  process.exit(1);
}
const source = readFileSync(activity, "utf8");
if (source.includes("setOnApplyWindowInsetsListener")) {
  console.log("[patch-android] activity already patched");
} else {
  const pkg = source.match(/^package\s+([\w.]+)/m)?.[1];
  if (!pkg) {
    console.error("[patch-android] no package line in MainActivity.kt");
    process.exit(1);
  }
  writeFileSync(
    activity,
    `package ${pkg}

import android.graphics.Color
import android.os.Bundle
import android.view.View
import androidx.core.view.ViewCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat

class MainActivity : TauriActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    WindowCompat.setDecorFitsSystemWindows(window, false)
    @Suppress("DEPRECATION")
    window.statusBarColor = Color.TRANSPARENT
    @Suppress("DEPRECATION")
    window.navigationBarColor = Color.TRANSPARENT
    WindowCompat.getInsetsController(window, window.decorView).apply {
      isAppearanceLightStatusBars = false
      isAppearanceLightNavigationBars = false
    }

    val root = findViewById<View>(android.R.id.content)
    root.setBackgroundColor(Color.parseColor("#2A2A2D"))
    ViewCompat.setOnApplyWindowInsetsListener(root) { view, insets ->
      val bars = insets.getInsets(
        WindowInsetsCompat.Type.systemBars() or
          WindowInsetsCompat.Type.displayCutout() or
          WindowInsetsCompat.Type.ime()
      )
      view.setPadding(bars.left, bars.top, bars.right, bars.bottom)
      WindowInsetsCompat.CONSUMED
    }
  }
}
`,
  );
  console.log("[patch-android] activity patched: page kept clear of the system bars");
}
